apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-external
  labels:
    service: ${APP_NAME}
spec:
  ports:
  - protocol: TCP
    port: ${EXTERNAL_PORT}
    targetPort: ${CONTAINER_PORT}
  selector:
    app: ${APP_NAME}
  type: LoadBalancer


